config_k=2
config_e=0.03
config_weightVsHint=0.5
config_numCandidates=1
config_numEvecs=1
config_lapOpVariant="paper"
config_lapOpShift=0.01
config_weightOpVariant="paper"
config_hintOpVariant="paper"
config_randLapCycles=1
config_lobpcgMaxIters=42
config_verbose=true
config_verbose_limits=[25, 500]
