#include "evo_partitioner.h"

#include <fstream>
#include <string>
#include <tbb/task_arena.h>
#include <csignal>

#include "evolutionary/combine.h"
#include "evolutionary/mutate.h"
#include "evolutionary/strategy_picker.h"
#include "mt-kahypar/partition/evolutionary/evo_logs.h"
#include "mt-kahypar/partition/partitioner.h"
#include "mt-kahypar/partition/multilevel.h"
#include "mt-kahypar/partition/recursive_bipartitioning.h"
#include "mt-kahypar/partition/deep_multilevel.h"
#include "mt-kahypar/partition/preprocessing/sparsification/degree_zero_hn_remover.h"
#include "mt-kahypar/partition/preprocessing/sparsification/large_he_remover.h"
#include "mt-kahypar/io/partitioning_output.h"
#ifdef KAHYPAR_ENABLE_STEINER_TREE_METRIC
#include "mt-kahypar/partition/mapping/initial_mapping.h"
#endif
#include "mt-kahypar/io/hypergraph_io.h"
#include "mt-kahypar/utils/timer.h"
#include "mt-kahypar/utils/utilities.h"

namespace mt_kahypar {
    static constexpr bool debug = true;

    template<typename TypeTraits>
    typename EvoPartitioner<TypeTraits>::PartitionedHypergraph EvoPartitioner<TypeTraits>::partition(
        Hypergraph& hypergraph, Context& context, TargetGraph* target_graph) {

        EvoPartitioner<TypeTraits>::configurePreprocessing(hypergraph, context);
        EvoPartitioner<TypeTraits>::setupContext(hypergraph, context, target_graph);

        io::printContext(context);
        io::printMemoryPoolConsumption(context);
        io::printInputInformation(context, hypergraph);

        #ifdef KAHYPAR_ENABLE_STEINER_TREE_METRIC
        bool map_partition_to_target_graph_at_the_end = false;
        if ( context.partition.objective == Objective::steiner_tree &&
            context.mapping.use_two_phase_approach ) {
        map_partition_to_target_graph_at_the_end = true;
        context.partition.objective = Objective::km1;
        context.setupGainPolicy();
        }
        #endif

        // init global timers for benchmark mode
        {
            std::lock_guard<std::mutex> lock(best_tracking_mutex_);
            global_best_fitness_ = std::numeric_limits<HyperedgeWeight>::max();
            global_best_time_ = std::chrono::milliseconds(0);
            improvement_log_entries.clear();
        }
        {
            std::lock_guard<std::mutex> lock(iteration_log_mutex);
            iteration_log_entries.clear();
        }
        {
            std::lock_guard<std::mutex> lock(population_summary_mutex);
            population_summary_entries.clear();
        }

        // DISABLED -- Individuals have incorrect indexing after preprocessing
        // ################## PREPROCESSING ##################
        utils::Timer& timer = utils::Utilities::instance().getTimer(context.utility_id);
        timer.start_timer("preprocessing", "Preprocessing");
        // DegreeZeroHypernodeRemover<TypeTraits> degree_zero_hn_remover(context);
        // LargeHyperedgeRemover<TypeTraits> large_he_remover(context);
        // Partitioner<TypeTraits>::preprocess(hypergraph, context, target_graph);
        // EvoPartitioner<TypeTraits>::sanitize(hypergraph, context, degree_zero_hn_remover, large_he_remover);
        timer.stop_timer("preprocessing");

        // ################## EVOLUTIONARY PARTITIONING ##################
        DBG << "DEBUG: Calling generateInitialPopulation...";
        // The initial population is generated by calling the standard partitioner repeatedly.
        Population population;
        std::string history = generateInitialPopulation(hypergraph, context, target_graph, population);
        DBG << "DEBUG: generateInitialPopulation finished.";

        DBG << "DEBUG: Calling performEvolution...";
        history += performEvolution(hypergraph, context, target_graph, population);
        DBG << "DEBUG: performEvolution finished.";

        if (context.evolutionary.history_file != "" && context.partition.enable_benchmark_mode) {
            std::ofstream out_stream(context.evolutionary.history_file.c_str(), 
                                   std::ios::out | std::ios::trunc); 
            out_stream << history;
            for (const auto& entry : improvement_log_entries) {
                out_stream << entry.timestamp << ", " << entry.operation_type << ", " << entry.km1 << "\n";
            }
            out_stream.close();
        }
        if (context.evolutionary.diff_matrix_file != "" && context.partition.enable_benchmark_mode) {
            std::ofstream out_stream(context.evolutionary.diff_matrix_file.c_str(),
                                   std::ios::out | std::ios::trunc);
            for (auto diff_matrix: diff_matrix_history) {
                std::string matrix_string;
                // return matrix as String
                for (size_t i = 0; i < diff_matrix.size(); i++) {
                    std::string row = Population::toString(diff_matrix[i]);
                    matrix_string += row + "\n";
                }
                // add separator between each matrix
                matrix_string += "---\n";
                out_stream << matrix_string;
            }
            out_stream.close();
        }
        if (context.evolutionary.enable_iteration_logging & context.partition.enable_benchmark_mode) {
            std::ofstream out_stream(context.evolutionary.iteration_log_file.c_str(),
                                   std::ios::out | std::ios::trunc);


           size_t line_count = iteration_log_entries.size();
           size_t log_limit = context.evolutionary.iteration_log_limit;

           // print every 1/line_countth line if limit is exceeded + last line
            if (line_count > log_limit) {
                    size_t step = line_count / log_limit;
                    for (size_t i = 0; i < line_count; ++i) {
                        if (i % step == 0 || i == line_count - 1) {
                            const auto& entry = iteration_log_entries[i];
                            out_stream << entry.iteration << ", " << entry.timestamp << ", " << entry.km1 << "\n";
                        }
                    }
            } else {
                for (const auto& entry : iteration_log_entries) {
                    out_stream << entry.iteration << ", " << entry.timestamp << ", " << entry.km1 << "\n";
                }
            }
            out_stream.close();
        }
        if (context.evolutionary.population_summary_file != "" && context.partition.enable_benchmark_mode) {
            std::ofstream out_stream(context.evolutionary.population_summary_file.c_str(),
                                   std::ios::out | std::ios::trunc);
            out_stream << "iteration,timestamp_ms,best_km1,median_km1,mean_km1,worst_km1,min_dist,median_dist,mean_dist,max_dist\n";
            for (const auto& entry : population_summary_entries) {
                out_stream << entry.iteration << "," << entry.timestamp << ","
                           << entry.best_km1 << "," << entry.median_km1 << ","
                           << entry.mean_km1 << "," << entry.worst_km1 << ","
                           << entry.min_distance << "," << entry.median_distance << ","
                           << entry.mean_distance << "," << entry.max_distance << "\n";
            }
            out_stream.close();
        }


        // ################## FINALIZATION ##################
        // After evolution, we take the best individual and create the final partition.
        PartitionedHypergraph final_partition(context.partition.k, const_cast<Hypergraph&>(hypergraph));
        
        std::vector<PartitionID> best_partition_vec = population.bestPartitionCopy();
        final_partition.doParallelForAllNodes([&](const HypernodeID& hn) {
            final_partition.setOnlyNodePart(hn, best_partition_vec[hn]);
        });
        final_partition.initializePartition();

        ASSERT([&] {
            bool success = true;
            if ( final_partition.hasFixedVertices() ) {
                for ( const HypernodeID& hn : final_partition.nodes() ) {
                    if ( final_partition.isFixed(hn) &&
                        final_partition.fixedVertexBlock(hn) != final_partition.partID(hn) ) {
                        LOG << "Node" << hn << "is fixed to block" << final_partition.fixedVertexBlock(hn)
                            << ", but is assigned to block" << final_partition.partID(hn);
                        success = false;
                    }
                }
            }
            return success;
        }(), "Some fixed vertices are not assigned to their corresponding block");

        // ################## POSTPROCESSING ##################
        timer.start_timer("postprocessing", "Postprocessing");
        // large_he_remover.restoreLargeHyperedges(final_partition);
        // degree_zero_hn_remover.restoreDegreeZeroHypernodes(final_partition);
        // forceFixedVertexAssignment(partitioned_hypergraph, context);
        timer.stop_timer("postprocessing");

        #ifdef KAHYPAR_ENABLE_STEINER_TREE_METRIC
            if ( map_partition_to_target_graph_at_the_end ) {
            ASSERT(target_graph);
            context.partition.objective = Objective::steiner_tree;
            timer.start_timer("one_to_one_mapping", "One-To-One Mapping");
            InitialMapping<TypeTraits>::mapToTargetGraph(
                 final_partition, *target_graph, context);
            timer.stop_timer("one_to_one_mapping");
            }
        #endif

        if (context.partition.enable_logging) {
            io::printHypergraphInfo(final_partition.hypergraph(), context,
                                    "Uncoarsened Hypergraph", context.partition.show_memory_consumption);
            io::printStripe();
        }

        return final_partition;
    }


    template<typename TypeTraits>
    std::string EvoPartitioner<TypeTraits>::generateInitialPopulation(const Hypergraph& hg, Context& context, TargetGraph* target_graph, Population& population) {
        context.partition.enable_logging = false;
        utils::Timer& timer = utils::Utilities::instance().getTimer(context.utility_id);
        auto start = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now().time_since_epoch());
        auto now = start;
        auto time_elapsed = now - start;
        auto duration = std::chrono::seconds(context.partition.time_limit);
        const bool enforce_time_limit = context.partition.time_limit > 0;
        std::string history = "Starttime: " + std::to_string(start.count()) + "\n";

        // META-EVO LOGIC
        if (context.evolutionary.meta_evo_mode) {
            DBG << "DEBUG: Starting Meta-Evo Initial Population Generation";
            

            int target_pop_size = context.evolutionary.population_size;
            int solutions_per_run = context.evolutionary.meta_evo_solutions_per_run; // Default 5
            int num_meta_runs = (target_pop_size + solutions_per_run - 1) / solutions_per_run;

            for (int run = 0; run < num_meta_runs; run++) {
                now = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now().time_since_epoch());
                if (context.partition.time_limit > 0 && (now - start) >= duration) {
                    DBG << "DEBUG: Meta-Evo aborted due to global time limit.";
                    break;
                }

                DBG << "DEBUG: Meta-Evo Run " << (run + 1) << "/" << num_meta_runs;

                // Setup Sub-Context
                Context sub_context(context);
                sub_context.evolutionary.meta_evo_mode = false; // Prevent recursion
                
                // Sub-runs use stopping criteria, NOT the global time limit
                sub_context.partition.time_limit = 0; 
                sub_context.evolutionary.improvement_rate_stopping.enabled = true;
                Population sub_population;

                // Adjust seed for sub-runs if in deterministic mode
                if (sub_context.partition.deterministic) {
                    sub_context.partition.seed += run + 1; // +1 to differ from main run
                }
                // Reset global state for this sub-run to ensure stopping criteria works correctly
                {
                    std::lock_guard<std::mutex> lock(best_tracking_mutex_);
                    global_best_fitness_ = std::numeric_limits<HyperedgeWeight>::max();
                    global_best_time_ = std::chrono::milliseconds(0);
                    improvement_log_entries.clear();
                }
                {
                    std::lock_guard<std::mutex> lock(iteration_log_mutex);
                    iteration_log_entries.clear();
                }
                {
                    std::lock_guard<std::mutex> lock(population_summary_mutex);
                    population_summary_entries.clear();
                }
                generateInitialPopulation(hg, sub_context, target_graph, sub_population);
                performEvolution(hg, sub_context, target_graph, sub_population);

                DBG << "DEBUG: Finished generating sub population";

                // Extract Best Individuals
                Individuals best_individuals = sub_population.listOfBest(solutions_per_run);
                for (auto individual : best_individuals) {
                    if (population.size() >= static_cast<size_t>(target_pop_size)) break;
                    population.addStartingIndividual(individual, context);
                }
            }
            auto end_time_meta = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now().time_since_epoch());
            auto meta_duration = std::chrono::duration_cast<std::chrono::seconds>(end_time_meta - start);
            // Update the global limit for the subsequent evolution phase
            if (context.partition.time_limit > 0) {
                context.partition.time_limit -= meta_duration.count();
                if (context.partition.time_limit < 1) context.partition.time_limit = 1; // leave at least 1 sec
            }

            context.partition.enable_logging = true;
            return history;
        }

        // if deterministic, save original seed to reset after initial population generation
        const int original_seed = context.partition.seed;
        if (context.partition.deterministic && context.partition.enable_benchmark_mode) {
            context.partition.seed = 0;
        }
               
        // INITIAL POPULATION
        if (context.evolutionary.dynamic_population_size) {
            HighResClockTimepoint start = std::chrono::high_resolution_clock::now();
            timer.start_timer("evolutionary", "Evolutionary");
            auto fitness = createInsertIndividual(hg, context, target_graph, population)->fitness();
            now = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now().time_since_epoch());

            // best result tracking for benchmark
            if (context.partition.enable_benchmark_mode) {
                checkAndLogNewBest(fitness, "Initial", now, context.evolutionary.iteration);
            }

            timer.stop_timer("evolutionary");

            ++context.evolutionary.iteration;
            int dynamic_population_size = std::round(context.evolutionary.dynamic_population_amount_of_time
                                                    * context.partition.time_limit
                                                    / timer.get("evolutionary"));
            int minimal_size = std::max(dynamic_population_size, 3);

            context.evolutionary.population_size = std::min(minimal_size, 50);
            // limit kway combine to population size
            context.evolutionary.kway_combine = std::min(context.evolutionary.kway_combine,
                                                        int(context.evolutionary.population_size));

            LOG << context.evolutionary.population_size;
            DBG << population;

            // increment seed if deterministic
            if (context.partition.deterministic) {
                context.partition.seed++;
            }
        }
        DBG << "DEBUG: Initial population target size =" << context.evolutionary.population_size;
        int best = std::numeric_limits<HyperedgeWeight>::max();
        int iteration = 0;

        while (population.size() < context.evolutionary.population_size &&
            (!enforce_time_limit || time_elapsed <= duration)) {
            DBG << "DEBUG: Initial pop loop - Iteration" << iteration << ", Pop size:" << population.size();
            ++context.evolutionary.iteration;
            timer.start_timer("evolutionary", "Evolutionary");
           
            auto cur = createInsertIndividual(hg, context, target_graph, population)->fitness();
            timer.stop_timer("evolutionary");
            now = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now().time_since_epoch());
            
            if (context.partition.enable_benchmark_mode) {
                checkAndLogNewBest(cur, "Initial", now, context.evolutionary.iteration);
            }
            
            // if (iteration == 0 || (cur < best)) {
            //     best = cur;
            //     history += "" + std::to_string(now.count()) + ", Repetition, " + std::to_string(cur) + "\n";
            // }
            iteration++;
            time_elapsed = now - start;

            // increment seed if in benchmark mode
            
            if (context.partition.deterministic) {
                context.partition.seed++;
            }
        }

        // reset seed after initial population generation
        if (context.partition.deterministic && context.partition.enable_benchmark_mode) {
            context.partition.seed = original_seed;
        }

        if (context.partition.enable_benchmark_mode) {
            std::lock_guard<std::mutex> lock(diff_matrix_history_mutex);
            DiffMatrix diff_matrix = population.updateDiffMatrix();
            diff_matrix_history.push_back(diff_matrix);
        }

        context.evolutionary.time_elapsed = time_elapsed;
        context.partition.enable_logging = true;
        return history;
    }
    template<typename TypeTraits>
    std::shared_ptr<Individual> EvoPartitioner<TypeTraits>::createIndividual(const Hypergraph &input_hg, Context &context,
                                                                       TargetGraph *target_graph) {
        Hypergraph hypergraph_copy = input_hg.copy(parallel_tag_t{});

        DBG << "DEBUG: generateIndividual: Calling standard partitioner...";

        Context ip_context(context);

        // If we are not using individual part weights, ensure max_part_weights is empty
        if (!ip_context.partition.use_individual_part_weights) {
            ip_context.partition.max_part_weights.clear();
        }

        // PREPROCESSING
        DegreeZeroHypernodeRemover<TypeTraits> degree_zero_hn_remover(context);
        LargeHyperedgeRemover<TypeTraits> large_he_remover(context);
        Partitioner<TypeTraits>::preprocess(hypergraph_copy, context, target_graph);
        EvoPartitioner<TypeTraits>::sanitize(hypergraph_copy, context, degree_zero_hn_remover, large_he_remover);

        EvoPartitioner<TypeTraits>::PartitionedHypergraph partitioned_hypergraph;
        // PartitionedHypergraph partitioned_hypergraph =
        //     Partitioner<TypeTraits>::partition(hypergraph_copy, ip_context, target_graph);
        vec<EdgeMetadata> edge_md;
        if (context.partition.mode == Mode::direct) {
            partitioned_hypergraph = Multilevel<TypeTraits>::partition(hypergraph_copy, std::move(edge_md), context, target_graph);
        } else if (context.partition.mode == Mode::recursive_bipartitioning) {
            partitioned_hypergraph = RecursiveBipartitioning<TypeTraits>::partition(hypergraph_copy,std::move(edge_md), context, target_graph);
        } else if (context.partition.mode == Mode::deep_multilevel) {
            partitioned_hypergraph = DeepMultilevel<TypeTraits>::partition(hypergraph_copy, context);
        } else {
            throw InvalidParameterException("Invalid partitioning mode!");
        }
        DBG << "DEBUG: generateIndividual: Partitioner finished.";

        // POSTPROCESSING
        large_he_remover.restoreSinglePinAndLargeHyperedges(partitioned_hypergraph);
        degree_zero_hn_remover.restoreDegreeZeroHypernodes(partitioned_hypergraph);
        //Partitioner<TypeTraits>::forceFixedVertexAssignment(partitioned_hypergraph, context);
        return std::make_shared<Individual>(partitioned_hypergraph, context);
    }

    template<typename TypeTraits>
    const std::shared_ptr<Individual>  EvoPartitioner<TypeTraits>::createInsertIndividual(const Hypergraph& input_hg, Context& context, TargetGraph* target_graph, Population& population) {
        auto individual = createIndividual(input_hg, context, target_graph);
        population.addStartingIndividual(individual, context);
        return individual;
    }

    template<typename TypeTraits>
    std::vector<PartitionID> EvoPartitioner<TypeTraits>::createPartition(const Hypergraph& input_hg, Context& context, TargetGraph* target_graph) {
        auto individual= createIndividual(input_hg, context, target_graph);
        return individual->partition();
    }

    template<typename TypeTraits>
    bool EvoPartitioner<TypeTraits>::insert_individual_into_population(std::shared_ptr<Individual> individual, const Context& context, Population& population, int iteration, const std::string& op_name) {
        individual->setBirthIteration(iteration);
        individual->setOriginOperator(op_name);
        bool improved = false;
        if (context.partition.enable_benchmark_mode) {
            auto time = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now().time_since_epoch());
            improved = checkAndLogNewBest(individual->fitness(), op_name, time, iteration);
        }
        size_t inserted_pos = population.insert(std::move(individual), context);
        bool was_accepted = (inserted_pos != std::numeric_limits<size_t>::max());
        if (constexpr int log_frequency = 1; context.partition.enable_benchmark_mode && (iteration % log_frequency == 0)) {
            std::lock_guard<std::mutex> lock(diff_matrix_history_mutex);
            DiffMatrix diff_matrix = population.updateDiffMatrix();
            diff_matrix_history.push_back(diff_matrix);

            if (context.evolutionary.population_summary_file != "") {
                std::lock_guard<std::mutex> sum_lock(population_summary_mutex);
                PopulationSummary summary = population.computeSummary();
                auto ts_ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                    std::chrono::high_resolution_clock::now().time_since_epoch()).count();
                population_summary_entries.push_back({
                    iteration, ts_ms,
                    static_cast<double>(summary.best_fitness),
                    static_cast<double>(summary.median_fitness),
                    summary.mean_fitness,
                    static_cast<double>(summary.worst_fitness),
                    summary.min_distance,
                    summary.median_distance,
                    summary.mean_distance,
                    summary.max_distance
                });
            }
        }
        return was_accepted;
    }

    template<typename TypeTraits>
    CombineResult EvoPartitioner<TypeTraits>::performCombine(
        const Hypergraph& input_hg,
        const Context& context,
        TargetGraph* target_graph,
        Population& population,
        ContextModifierParameters modified_combine_params,
        std::mt19937* rng
        ) {

        EvoCombineStrategy combine_strategy = pick::decideNextCombination(context, rng);
        switch (combine_strategy) {
            case EvoCombineStrategy::basic:
                return {
                    combine::usingKWaySelection<TypeTraits>(input_hg,population, context, target_graph, rng),
                    combine_strategy,
                };
            case EvoCombineStrategy::edge_frequency:
                return {
                    combine::usingMultiEdgeFrequency<TypeTraits>(input_hg, population, context, target_graph, rng),
                    combine_strategy,
                };
            case EvoCombineStrategy::synthetic_parent:
                // decide modified combine parameters if mixed strategy is enabled
                if (context.evolutionary.modified_combine_mixed) {
                    modified_combine_params = pick::decideContextModificationParameters(context, rng);
                }
                return {
                    combine::usingSyntheticSecondParent<TypeTraits>(input_hg, population, target_graph, modified_combine_params, context, rng),
                    combine_strategy,
                };
            case EvoCombineStrategy::UNDEFINED:
                break;
        }
    }

    template<typename TypeTraits>
    MutationResult EvoPartitioner<TypeTraits>::performMutation(
        const Hypergraph &input_hg,
        const Context &context,
        TargetGraph *target_graph,
        Population &population,
        std::mt19937 *rng) {
    Hypergraph hypergraph = input_hg.copy(parallel_tag_t{});

    const std::vector rnd_ind_partition(population.randomIndividualPartitionCopy(context.partition.deterministic, rng));
    EvoMutateStrategy mutate_strategy = pick::decideNextMutation(context, rng);
    switch (mutate_strategy) {
        case EvoMutateStrategy::new_initial_partitioning_vcycle:
            return {
                mutate::vCycleWithNewInitialPartitioning<TypeTraits>(hypergraph, rnd_ind_partition, target_graph,
                                                                            context),
                mutate_strategy
            };
        case EvoMutateStrategy::vcycle:
            return {
                mutate::vCycle<TypeTraits>(hypergraph, rnd_ind_partition, target_graph, context),
                mutate_strategy
            };
        case EvoMutateStrategy::UNDEFINED:
            throw UnsupportedOperationException("Next Mutation Strategy is UNDEFINED");
    }
    }

    inline void disableTimerAndStatsEvo(const Context& context) {
        if ( context.type == ContextType::main && context.partition.mode == Mode::direct ) {
            utils::Utilities& utils = utils::Utilities::instance();
            parallel::MemoryPool::instance().deactivate_unused_memory_allocations();
            utils.getTimer(context.utility_id).disable();
            utils.getStats(context.utility_id).disable();
        }
    }

    inline void enableTimerAndStatsEvo(const Context& context) {
        if ( context.type == ContextType::main && context.partition.mode == Mode::direct ) {
            utils::Utilities& utils = utils::Utilities::instance();
            parallel::MemoryPool::instance().activate_unused_memory_allocations();
            utils.getTimer(context.utility_id).enable();
            utils.getStats(context.utility_id).enable();
        }
    }

    template<typename TypeTraits>
    std::string EvoPartitioner<TypeTraits>::performEvolution(const Hypergraph& hg, Context& context, TargetGraph* target_graph, Population& population) {
        context.partition.enable_logging = false;
        int timelimit = context.partition.time_limit;
        utils::Timer& timer = utils::Utilities::instance().getTimer(context.utility_id);
        auto time_start = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::high_resolution_clock::now().time_since_epoch());
        std::string history = "";
        const bool enforce_time_limit = timelimit > 0;
        auto duration = std::chrono::seconds(timelimit) - context.evolutionary.time_elapsed;
        std::atomic<bool> stop_flag(false);

        const int total_threads = context.shared_memory.num_threads;
        int num_evo_workers = 0;
        int num_multilevel_threads = 0;

        if (context.evolutionary.num_threads_per_worker > 0) {
            num_multilevel_threads = std::min(total_threads, static_cast<int>(context.evolutionary.num_threads_per_worker));
            num_evo_workers = std::max(1, total_threads / num_multilevel_threads);
        } else {
            // Default behavior
            num_evo_workers = std::max(1, total_threads / 2);
            num_multilevel_threads = std::max(1, total_threads / num_evo_workers);
        }
        
        std::atomic<int> total_mutations(0);
        std::atomic<int> total_combinations(0);
        std::atomic<int> total_basic_combinations(0);
        std::atomic<int> total_edge_frequency_combinations(0);
        std::atomic<int> total_synthetic_parent_combinations(0);
        std::atomic<int> total_iterations(0);

        // Per-operator yield tracking
        std::atomic<int> attempts_vcycle_mutation(0);
        std::atomic<int> accepted_vcycle_mutation(0);
        std::atomic<int> attempts_new_init_mutation(0);
        std::atomic<int> accepted_new_init_mutation(0);

        std::atomic<int> attempts_basic_combine(0);
        std::atomic<int> accepted_basic_combine(0);
        std::atomic<int> attempts_edge_freq_combine(0);
        std::atomic<int> accepted_edge_freq_combine(0);
        std::atomic<int> attempts_synthetic_combine(0);
        std::atomic<int> accepted_synthetic_combine(0);

        // State for stopping criterion
        double early_window_improvement_rate = -1.0;
        std::mutex stopping_criterion_mutex;

        // Calculate ContextModifierParameters once before any workers start
        ContextModifierParameters modified_combine_params;
        if (context.evolutionary.synthetic_parent_combine_weight > 0) {
            const double k_result = context.partition.k * context.evolutionary.modified_combine_k_multiplier;
            ASSERT(k_result >= 1.0, "k multiplier result must be >= 1: " << k_result);
            ASSERT(std::abs(k_result - std::round(k_result)) < 1e-10, 
                "k multiplier must result in whole number: " << k_result);
            
            const PartitionID absolute_k = static_cast<PartitionID>(std::round(k_result));
            const double absolute_epsilon = std::min(0.99, 
                context.partition.epsilon * context.evolutionary.modified_combine_epsilon_multiplier);
            
            modified_combine_params = ContextModifierParameters{
                .use_random_partitions = context.evolutionary.modified_combine_use_random_partitions,
                .use_degree_sorted_partitions = context.evolutionary.modified_combine_use_degree_sorted_partitions,
                .k = absolute_k,
                .epsilon = absolute_epsilon,
                .recursive_bipartitioning = context.evolutionary.modified_combine_recursive_bipartitioning
            };
        }

        timer.start_timer("evolutionary", "Evolutionary");

        LOG << "Starting evolutionary search with" << num_evo_workers << "workers, each using"
            << num_multilevel_threads << "threads for multilevel partitioning.";

        const bool iteration_logging_enabled = context.evolutionary.enable_iteration_logging & context.partition.enable_benchmark_mode;
        const size_t log_limit = std::max<size_t>(1, context.evolutionary.iteration_log_limit);

        const auto create_worker_arenas = [&]() {
            std::vector<std::unique_ptr<tbb::task_arena>> worker_arenas;
            worker_arenas.reserve(static_cast<size_t>(num_evo_workers));
            for (int i = 0; i < num_evo_workers; ++i) {
                worker_arenas.push_back(std::make_unique<tbb::task_arena>(num_multilevel_threads));
            }
            return worker_arenas;
        };

        const auto reached_global_stop_condition = [&]() {
            const auto now = std::chrono::duration_cast<std::chrono::milliseconds>(
              std::chrono::high_resolution_clock::now().time_since_epoch());
            if (enforce_time_limit && (now - time_start >= duration)) {
                stop_flag = true;
                return true;
            }
            if (context.evolutionary.max_iterations != 0 &&
                total_iterations.load(std::memory_order_relaxed) >= context.evolutionary.max_iterations) {
                stop_flag = true;
                return true;
            }
            return false;
        };


        const int global_seed = context.partition.seed;
        //standard mode non-deterministic
        if (!context.partition.deterministic) {
            // task arenas for each worker to ensure isolated thread pools
            auto worker_arenas = create_worker_arenas();

            tbb::parallel_for(0, num_evo_workers, [&](int worker_id) {
                // Each evo worker uses own arena
                worker_arenas[worker_id]->execute([&] {
                    while (!stop_flag) {
                        if (reached_global_stop_condition()) {
                            break;
                        }
                        if (context.evolutionary.improvement_rate_stopping.enabled) {
                            std::unique_lock<std::mutex> stop_lock(stopping_criterion_mutex, std::try_to_lock);
                            if (stop_lock.owns_lock()) {
                                std::lock_guard<std::mutex> iter_lock(iteration_log_mutex);
                                std::lock_guard<std::mutex> best_lock(best_tracking_mutex_);

                                int last_improv_iter = -1;
                                if (!improvement_log_entries.empty()) {
                                    last_improv_iter = improvement_log_entries.back().iteration;
                                }

                                bool should_stop = evolutionary::stopping::sliding_window_improvement_rate_stop(
                                    last_improv_iter,
                                    improvement_log_entries,
                                    iteration_log_entries,
                                    context.evolutionary.improvement_rate_stopping.early_window_improvs,
                                    context.evolutionary.improvement_rate_stopping.recent_window_improvs,
                                    context.evolutionary.improvement_rate_stopping.alpha,
                                    context.evolutionary.improvement_rate_stopping.max_iters_without_improv,
                                    early_window_improvement_rate
                                );

                                if (should_stop) {
                                    stop_flag = true;
                                    break;
                                }
                            }
                        }

                        // Create a context for the inner run and set its thread limit
                        Context evo_context(context);
                        evo_context.type = ContextType::main;
                        evo_context.utility_id = utils::Utilities::instance().registerNewUtilityObjects();
                        evo_context.shared_memory.num_threads = num_multilevel_threads;

                        EvoDecision decision = pick::decideNextMove(context);
                        EvoPartitioner<TypeTraits>::Hypergraph hg_copy = hg.copy(parallel_tag_t{});

                        // Ensure sanityCheck preconditions hold for any standard partitioning
                        // calls executed within workers by keeping part weights vector empty
                        // unless individual part weights are explicitly enabled by the user.
                        if (!evo_context.partition.use_individual_part_weights) {
                            evo_context.partition.max_part_weights.clear();
                        }
                        
                        switch (decision) {
                            case EvoDecision::mutation:
                                {
                                    auto mut_result = performMutation(hg_copy, evo_context, target_graph, population);
                                    std::string op_name = (mut_result.strategy == EvoMutateStrategy::vcycle) ? "vCycle_Mutate" : "NewInit_Mutate";
                                    if (mut_result.strategy == EvoMutateStrategy::vcycle) {
                                        attempts_vcycle_mutation.fetch_add(1, std::memory_order_relaxed);
                                    } else {
                                        attempts_new_init_mutation.fetch_add(1, std::memory_order_relaxed);
                                    }
                                    bool was_accepted = insert_individual_into_population(mut_result.individual, evo_context, population, total_iterations.load() + 1, op_name);
                                    if (was_accepted) {
                                        if (mut_result.strategy == EvoMutateStrategy::vcycle) {
                                            accepted_vcycle_mutation.fetch_add(1, std::memory_order_relaxed);
                                        } else {
                                            accepted_new_init_mutation.fetch_add(1, std::memory_order_relaxed);
                                        }
                                    }
                                    total_mutations++;
                                    total_iterations++;
                                    break;
                                }
                            case EvoDecision::combine:
                                {
                                    const CombineResult result = performCombine(hg_copy, evo_context, target_graph, population, modified_combine_params);
                                    std::string op_name = "Basic_Combine";
                                    if (result.strategy == EvoCombineStrategy::basic) {
                                        attempts_basic_combine.fetch_add(1, std::memory_order_relaxed);
                                        op_name = "Basic_Combine";
                                    } else if (result.strategy == EvoCombineStrategy::edge_frequency) {
                                        attempts_edge_freq_combine.fetch_add(1, std::memory_order_relaxed);
                                        op_name = "EdgeFreq_Combine";
                                    } else if (result.strategy == EvoCombineStrategy::synthetic_parent) {
                                        attempts_synthetic_combine.fetch_add(1, std::memory_order_relaxed);
                                        op_name = "Synthetic_Combine";
                                    }
                                    bool was_accepted = insert_individual_into_population(result.individual, evo_context, population, total_iterations.load() + 1, op_name);
                                    if (was_accepted) {
                                        if (result.strategy == EvoCombineStrategy::basic) {
                                            accepted_basic_combine.fetch_add(1, std::memory_order_relaxed);
                                        } else if (result.strategy == EvoCombineStrategy::edge_frequency) {
                                            accepted_edge_freq_combine.fetch_add(1, std::memory_order_relaxed);
                                        } else if (result.strategy == EvoCombineStrategy::synthetic_parent) {
                                            accepted_synthetic_combine.fetch_add(1, std::memory_order_relaxed);
                                        }
                                    }
                                    total_combinations++;
                                    total_iterations++;
                                switch (result.strategy) {
                                    case EvoCombineStrategy::basic:
                                        ++total_basic_combinations;
                                        break;
                                    case EvoCombineStrategy::edge_frequency:
                                        ++total_edge_frequency_combinations;
                                        break;
                                    case EvoCombineStrategy::synthetic_parent:
                                        ++total_synthetic_parent_combinations;
                                        break;
                                    default:
                                        break;
                                }
                                    break;
                                }
                            default:
                                LOG << "Error in evo_partitioner.cpp: Non-covered case in decision making";
                                std::exit(EXIT_FAILURE);
                        }

                        // Log current best KM1 after each iteration if enabled (iteration, timestamp, km1)
                        if ( iteration_logging_enabled ) {
                            // get current best KM1 from population
                            auto current_km1 = population.bestInd()->fitness();
                            auto ts_ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                                            std::chrono::high_resolution_clock::now().time_since_epoch()
                                            ).count();
                            std::lock_guard<std::mutex> lg(iteration_log_mutex);
                            iteration_log_entries.push_back({total_iterations.load(), ts_ms, static_cast<double>(current_km1)});
                        }
                    }
                });
            });
        }
        else {
            //determinstic mode
            const int batch_size = context.evolutionary.batch_size;
            std::vector<std::shared_ptr<Individual>> batch_individuals (batch_size);
            std::atomic<size_t> last_batch_filled = 0;
            std::atomic<int> items_finished_in_current_batch = 0;

            auto worker_arenas = create_worker_arenas();

            tbb::parallel_for(0, num_evo_workers, [&](int worker_id) {
                // Each evo worker uses its own arena
                worker_arenas[worker_id]->execute([&] {

                    while (!stop_flag) {
                        if (reached_global_stop_condition()) {
                            break;
                        }

                        int iteration_id = -1;
                        int batch_id = -1;
                        int batch_pos = -1;
                        while (true) {
                            const int cur = total_iterations.load(std::memory_order_relaxed);
                            const int cur_batch = cur / batch_size;

                            while (static_cast<size_t>(cur_batch) > last_batch_filled.load(std::memory_order_acquire)) {
                                if (stop_flag.load(std::memory_order_acquire)) {
                                    break;
                                }
                                std::this_thread::yield();
                            }
                            if (stop_flag.load(std::memory_order_acquire)) {
                                break;
                            }

                            int expected = cur;
                            if (total_iterations.compare_exchange_weak(expected, cur + 1, std::memory_order_acq_rel, std::memory_order_relaxed)) {
                                iteration_id = cur;
                                batch_id = cur_batch;
                                batch_pos = cur % batch_size;
                                break;
                            }
                        }
                        if (stop_flag.load(std::memory_order_acquire)) {
                            break;
                        }

                        // Create a thread-local copy of the context
                        Context evo_context(context);
                        evo_context.type = ContextType::main;
                        evo_context.utility_id = utils::Utilities::instance().registerNewUtilityObjects();
                        evo_context.shared_memory.num_threads = num_multilevel_threads;


                        evo_context.partition.seed = global_seed + iteration_id;

                        // Initialize task-local RNG
                        std::mt19937 rng(evo_context.partition.seed);

                        EvoDecision decision = pick::decideNextMove(evo_context, &rng);
                        Hypergraph hg_copy = hg.copy(parallel_tag_t{});
                        std::shared_ptr<Individual> child;

                        std::string op_name = "Unknown";
                        switch (decision) {
                            case EvoDecision::mutation: {
                                auto mut_result = performMutation(hg_copy, evo_context, target_graph, population, &rng);
                                op_name = (mut_result.strategy == EvoMutateStrategy::vcycle) ? "vCycle_Mutate" : "NewInit_Mutate";
                                if (mut_result.strategy == EvoMutateStrategy::vcycle) {
                                    attempts_vcycle_mutation.fetch_add(1, std::memory_order_relaxed);
                                } else {
                                    attempts_new_init_mutation.fetch_add(1, std::memory_order_relaxed);
                                }
                                child = std::move(mut_result.individual);
                                total_mutations.fetch_add(1, std::memory_order_relaxed);
                                break;
                            }
                            case EvoDecision::combine: {
                                auto result = performCombine(hg_copy, evo_context, target_graph, population, modified_combine_params, &rng);
                                if (result.strategy == EvoCombineStrategy::basic) {
                                    attempts_basic_combine.fetch_add(1, std::memory_order_relaxed);
                                    op_name = "Basic_Combine";
                                } else if (result.strategy == EvoCombineStrategy::edge_frequency) {
                                    attempts_edge_freq_combine.fetch_add(1, std::memory_order_relaxed);
                                    op_name = "EdgeFreq_Combine";
                                } else if (result.strategy == EvoCombineStrategy::synthetic_parent) {
                                    attempts_synthetic_combine.fetch_add(1, std::memory_order_relaxed);
                                    op_name = "Synthetic_Combine";
                                }
                                child = std::move(result.individual);
                                total_combinations.fetch_add(1, std::memory_order_relaxed);
                                switch (result.strategy) {
                                   case EvoCombineStrategy::basic:
                                        total_basic_combinations.fetch_add(1, std::memory_order_relaxed);
                                        break;
                                    case EvoCombineStrategy::edge_frequency:
                                        total_edge_frequency_combinations.fetch_add(1, std::memory_order_relaxed);
                                        break;
                                    case EvoCombineStrategy::synthetic_parent:
                                        total_synthetic_parent_combinations.fetch_add(1, std::memory_order_relaxed);
                                        break;
                                    default:
                                        break;
                                }
                                break;
                            }
                            default:
                                LOG << "Error: Non-covered case in decision making";
                                std::exit(EXIT_FAILURE);
                        }

                        // Store individual in batch
                        child->setOriginOperator(op_name);
                        batch_individuals[static_cast<size_t>(batch_pos)] = std::move(child);
                        
                        int finished_count = items_finished_in_current_batch.fetch_add(1, std::memory_order_acq_rel) + 1;

                        if (finished_count == batch_size) {
                            // Insert entire batch into population
                            for (size_t i = 0; i < batch_size; ++i) {
                                const int current_batch_start_id = batch_id * batch_size;
                                std::string cur_op = batch_individuals[i]->originOperator();
                                bool was_accepted = insert_individual_into_population(std::make_unique<Individual>(std::move(*batch_individuals[i])), evo_context, population, current_batch_start_id + static_cast<int>(i) + 1, cur_op);
                                if (was_accepted) {
                                    if (cur_op == "vCycle_Mutate") accepted_vcycle_mutation.fetch_add(1, std::memory_order_relaxed);
                                    else if (cur_op == "NewInit_Mutate") accepted_new_init_mutation.fetch_add(1, std::memory_order_relaxed);
                                    else if (cur_op == "Basic_Combine") accepted_basic_combine.fetch_add(1, std::memory_order_relaxed);
                                    else if (cur_op == "EdgeFreq_Combine") accepted_edge_freq_combine.fetch_add(1, std::memory_order_relaxed);
                                    else if (cur_op == "Synthetic_Combine") accepted_synthetic_combine.fetch_add(1, std::memory_order_relaxed);
                                }

                                if (iteration_logging_enabled) {
                                // One "iteration" per inserted individual
                                auto current_km1 = population.bestInd()->fitness();
                                auto ts_ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                                                std::chrono::high_resolution_clock::now().time_since_epoch()
                                            ).count();
                                std::lock_guard<std::mutex> lg(iteration_log_mutex);
                                iteration_log_entries.push_back({current_batch_start_id + static_cast<int>(i) + 1, ts_ms, static_cast<double>(current_km1)});
                                }  
                            }

                            // Deterministic stopping criterion evaluation at batch boundaries
                            if (context.evolutionary.improvement_rate_stopping.enabled &&
                                !stop_flag.load(std::memory_order_acquire)) {
                                std::lock_guard<std::mutex> stop_lock(stopping_criterion_mutex);
                                std::lock_guard<std::mutex> iter_lock(iteration_log_mutex);
                                std::lock_guard<std::mutex> best_lock(best_tracking_mutex_);

                                int last_improv_iter = -1;
                                if (!improvement_log_entries.empty()) {
                                    last_improv_iter = improvement_log_entries.back().iteration;
                                }

                                const bool should_stop = evolutionary::stopping::sliding_window_improvement_rate_stop(
                                    last_improv_iter,
                                    improvement_log_entries,
                                    iteration_log_entries,
                                    context.evolutionary.improvement_rate_stopping.early_window_improvs,
                                    context.evolutionary.improvement_rate_stopping.recent_window_improvs,
                                    context.evolutionary.improvement_rate_stopping.alpha,
                                    context.evolutionary.improvement_rate_stopping.max_iters_without_improv,
                                    early_window_improvement_rate
                                );

                                if (should_stop) {
                                    stop_flag.store(true, std::memory_order_release);
                                }
                            }

                            // Mark batch as filled
                            items_finished_in_current_batch.store(0, std::memory_order_release);
                            last_batch_filled.fetch_add(1, std::memory_order_release);
                        } 

                    } 
                });
            });
        }



        timer.stop_timer("evolutionary");

        // Update final diff matrix
        if (context.partition.enable_benchmark_mode) {
            std::lock_guard<std::mutex> lock(diff_matrix_history_mutex);
            DiffMatrix diff_matrix = population.updateDiffMatrix();
            diff_matrix_history.push_back(diff_matrix);
        }

        context.evolutionary.iteration += total_iterations.load();
        context.partition.enable_logging = true;
        LOG << "Performed " << total_iterations.load() << " Evolutionary Iterations";
        LOG << "  " << total_mutations.load() << " Mutations";
        LOG << "  " << total_combinations.load() << " Combinations";
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_iterations", static_cast<int64_t>(total_iterations.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_mutations", static_cast<int64_t>(total_mutations.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_combinations", static_cast<int64_t>(total_combinations.load()));
        if (context.evolutionary.basic_combine_weight > 0) {
            LOG << "    " << total_basic_combinations.load() << " Basic";
            utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_basic_combinations", static_cast<int64_t>(total_basic_combinations.load()));
        }
        if (context.evolutionary.edge_frequency_combine_weight > 0) {
            LOG << "    " << total_edge_frequency_combinations.load() << " Edge Frequency";
            utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_edge_frequency_combinations", static_cast<int64_t>(total_edge_frequency_combinations.load()));
        }
        if (context.evolutionary.synthetic_parent_combine_weight > 0) {
            LOG << "    " << total_synthetic_parent_combinations.load() << " Synthetic Parent";
            utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_synthetic_parent_combinations", static_cast<int64_t>(total_synthetic_parent_combinations.load()));
        }
        LOG << "===================================================";
        LOG << "Operator Yield Statistics";
        const auto print_op_stat = [&](const std::string& name, int attempts, int accepted) {
            double rate = attempts > 0 ? (static_cast<double>(accepted) / attempts) * 100.0 : 0.0;
            LOG << "  " << name << ": " << attempts << " attempts | " << accepted << " accepted (" << rate << "%)";
        };
        print_op_stat("Basic Combine", attempts_basic_combine.load(), accepted_basic_combine.load());
        print_op_stat("Edge Frequency Combine", attempts_edge_freq_combine.load(), accepted_edge_freq_combine.load());
        print_op_stat("Synthetic Parent Combine", attempts_synthetic_combine.load(), accepted_synthetic_combine.load());
        print_op_stat("vCycle Mutation", attempts_vcycle_mutation.load(), accepted_vcycle_mutation.load());
        print_op_stat("New Initial Part Mutation", attempts_new_init_mutation.load(), accepted_new_init_mutation.load());

        LOG << "===================================================";
        LOG << "Population Slot Replacement Heatmap";
        std::vector<size_t> slot_reps = population.slotReplacements();
        size_t untouched_slots = 0;
        size_t max_reps = 0;
        for (size_t i = 0; i < slot_reps.size(); ++i) {
            if (slot_reps[i] == 0) untouched_slots++;
            if (slot_reps[i] > max_reps) max_reps = slot_reps[i];
        }
        LOG << "  Total slots: " << slot_reps.size() << " | Untouched (alive since init): " << untouched_slots << " | Max overwrites on single slot: " << max_reps;

        LOG << "===================================================";
        LOG << "Insertion Statistics";
        LOG << "  " << population.total_insert_attempts.load() << " total insertion attempts";
        LOG << "  " << population.accepted_replacement.load() << " accepted insertions";
        LOG << "  " << population.rejected_worse_than_worst.load() << " rejected because worse than worst";
        const size_t total = population.total_insert_attempts.load();
        const size_t rejected = population.rejected_worse_than_worst.load();
        const double percentage = total > 0 ? (static_cast<double>(rejected) / total) * 100.0 : 0.0;
        LOG << "  " << percentage << "% rejection percentage";

        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_basic_combine_attempts", static_cast<int64_t>(attempts_basic_combine.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_basic_combine_accepted", static_cast<int64_t>(accepted_basic_combine.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_edge_freq_combine_attempts", static_cast<int64_t>(attempts_edge_freq_combine.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_edge_freq_combine_accepted", static_cast<int64_t>(accepted_edge_freq_combine.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_synthetic_combine_attempts", static_cast<int64_t>(attempts_synthetic_combine.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_synthetic_combine_accepted", static_cast<int64_t>(accepted_synthetic_combine.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_vcycle_mutation_attempts", static_cast<int64_t>(attempts_vcycle_mutation.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_vcycle_mutation_accepted", static_cast<int64_t>(accepted_vcycle_mutation.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_new_init_mutation_attempts", static_cast<int64_t>(attempts_new_init_mutation.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_new_init_mutation_accepted", static_cast<int64_t>(accepted_new_init_mutation.load()));

        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_insertion_attempts", static_cast<int64_t> (population.total_insert_attempts.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_accepted_replacements", static_cast<int64_t>(population.accepted_replacement.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_rejected_worse_than_worst", static_cast<int64_t>(population.rejected_worse_than_worst.load()));
        utils::Utilities::instance().getStats(context.utility_id).add_stat("evo_rejection_percentage", percentage);
        return history;
    }

    // Static member definitions for all TypeTraits (template required)
    template<typename TypeTraits>
    std::mutex EvoPartitioner<TypeTraits>::best_tracking_mutex_;

    template<typename TypeTraits>
    HyperedgeWeight EvoPartitioner<TypeTraits>::global_best_fitness_ = std::numeric_limits<HyperedgeWeight>::max();

    template<typename TypeTraits>
    std::chrono::milliseconds EvoPartitioner<TypeTraits>::global_best_time_{ 0 };

    template<typename TypeTraits>
    bool EvoPartitioner<TypeTraits>::checkAndLogNewBest(
        HyperedgeWeight fitness,
        const std::string& operation_type,
        std::chrono::milliseconds current_time,
        int iteration) {
    
        std::lock_guard<std::mutex> lock(best_tracking_mutex_);
        
        if (fitness < global_best_fitness_) {
            global_best_fitness_ = fitness;
            global_best_time_ = current_time;
            
            improvement_log_entries.push_back({current_time.count(), iteration, static_cast<double>(fitness), operation_type});
            return true;
        }
    
        return false;
    }

template<typename TypeTraits>
std::vector<DiffMatrix> EvoPartitioner<TypeTraits>::diff_matrix_history;

template<typename TypeTraits>
std::mutex EvoPartitioner<TypeTraits>::diff_matrix_history_mutex;

template<typename TypeTraits>
std::vector<evolutionary::IterationLogEntry>
EvoPartitioner<TypeTraits>::iteration_log_entries;

template<typename TypeTraits>
std::mutex EvoPartitioner<TypeTraits>::iteration_log_mutex;

template<typename TypeTraits>
std::vector<evolutionary::ImprovementLogEntry>
EvoPartitioner<TypeTraits>::improvement_log_entries;

template<typename TypeTraits>
std::vector<evolutionary::PopulationSummaryLogEntry>
EvoPartitioner<TypeTraits>::population_summary_entries;

template<typename TypeTraits>
std::mutex EvoPartitioner<TypeTraits>::population_summary_mutex;

template<typename TypeTraits>
thread_local std::vector<std::unique_ptr<Individual>> EvoPartitioner<TypeTraits>::thread_local_temporaries_;


}  // namespace mt_kahypar